<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <RootNamespace>EgoEngineLibrary.Frontend</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EgoEngineLibrary.Frontend\EgoEngineLibrary.Frontend.csproj" />
  </ItemGroup>

</Project>
